### ISSUE TITLE
[BUG]rss插件cache文件夹不会自动创建

### ISSUE THREAD

**Issue by Suiyi-Light** [crowya/yaya-plugins-for-argon#1]
rss插件不会自动创建cache，手动创建cache文件夹后可正常

Warning: */plugins/yaya-links-rss/cache is not writable. Make sure you've set the correct relative or absolute path, and that the location is server-writable. in */wp-includes/class-simplepie.php on line 1566

**Comment by crowya** [comment]
谢谢提醒，已为大家预先创建`cache`空文件夹。
