### ISSUE TITLE
ip属地显示不正确

### ISSUE THREAD

**Issue by Qrasa510** [crowya/yaya-plugins-for-argon#2]
![image](https://github.com/crowya/yaya-plugins-for-argon/assets/141288648/d27581bf-0e73-4e28-a593-c15a17cabeb6)

**Comment by Qrasa510** [comment]
注：服务器在香港，用户在国内

**Comment by 1ctrl-cv** [comment]
插眼

**Comment by crowya** [comment]
今天更新了一下IP数据库，可以试下替换qqwry.dat这个文件，以后更新的话也可以关注下这个：https://github.com/metowolf/qqwry.dat
但是不知道能不能解决你的问题~

**Comment by Qrasa510** [comment]
现在好啦，有点误差但是可以忽略
